routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return redirect()->route('contact.create');
// });
Route::get('/', 'LoginController@index')->name('login.index');
Route::get('login', 'LoginController@index')->name('login.index');
Route::post('login', 'LoginController@processlogin')->name('login.processlogin');
Route::get('logout', 'LoginController@logout');
Route::get('forgotpassword', 'LoginController@forgotpassword')->name('login.forgotpassword');
Route::post('forgotpassword', 'LoginController@processforgotpass')->name('login.processforgotpass');
Route::get('adjustleavebalance', 'LoginController@adjustLeaveBalance');


Route::group(['middleware' => 'checkLogin'], function () {
  Route::resource('employee', 'EmployeeController')->middleware('userAuth');
  Route::get('employee/document/{id}', 'EmployeeController@document')->where(['id'=>'[0-9]+']);
  Route::post('employee/documentupload', 'EmployeeController@documentupload');
  Route::get('employee/document_edit/{id}', 'EmployeeController@document_edit')->where(['id'=>'[0-9]+']);
  Route::post('employee/document_update', 'EmployeeController@document_update');
  Route::get('employee/document_destroy/{id}', 'EmployeeController@document_destroy')->where(['id'=>'[0-9]+']);

  Route::get('dashboard', 'DashboardController@index');
  Route::get('dashboard/profile_edit', 'DashboardController@profile_edit');
  Route::post('dashboard/updateprofile', 'DashboardController@updateprofile')->name('dashboard.updateprofile');

  Route::get('leave/create', 'LeaveController@create')->name('leave.create');
  Route::post('leave/create', 'LeaveController@store')->name('leave.store');
  Route::post('leave/getDateRange', 'LeaveController@getDateRange');
  Route::get('leave', 'LeaveController@index')->name('leave.view');
  Route::get('leave/edit/{id}', 'LeaveController@edit')->where(['id'=>'[0-9]+']);
  Route::post('leave/update', 'LeaveController@update')->name('leave.update');
  Route::get('leave/leaverequests', 'LeaveController@leaverequests')->middleware('userAuth')->name('leave.leaverequests');
  Route::get('leave/detail/{id}', 'LeaveController@detail')->name('leave.detail');
  Route::post('leave/statusupdate', 'LeaveController@statusupdate')->name('leave.statusupdate');
  Route::get('leave/destroy/{id}', 'LeaveController@destroy')->where(['id'=>'[0-9]+'])->name('leave.destroy');
  Route::post('leave/getLeaveInfo', 'LeaveController@getLeaveInfo')->name('leave.info');

  Route::get('policy', 'PolicyController@index')->name('policy.index');
  Route::get('policy/edit', 'PolicyController@edit')->middleware('userAuth')->name('policy.edit');
  Route::post('policy/update', 'PolicyController@update')->name('policy.update');

  Route::resource('holiday', 'HolidayController',['except'=>['index']])->middleware('userAuth');
  Route::get('holiday', 'HolidayController@index')->name('holiday.index');

  Route::get('feedback', 'FeedbackController@index')->name('feedback.index');
  Route::post('feedback', 'FeedbackController@store')->name('feedback.store');
  Route::get('feedback/view', 'FeedbackController@view')->middleware('userAuth')->name('feedback.view');
  Route::get('feedback/getfeedback/{id}', 'FeedbackController@getfeedback')->middleware('userAuth')->name('feedback.getfeedback');
  Route::post('feedback/getPreviousChat', 'FeedbackController@getPreviousChat');

  Route::get('salary','SalaryController@index')->name('salary.index');
  Route::post('salary','SalaryController@getSalaryDetail')->name('salary.detail');
  Route::get('salary/create', 'SalaryController@create')->middleware('userAuth')->name('salary.create');
  Route::get('salary/overview/{id}', 'SalaryController@overview')->middleware('userAuth')->name('salary.overview')->where(['id'=>'[0-9]+']);
  Route::post('salary/generateSalary', 'SalaryController@generateSalary')->name('salary.generatesalary');
  Route::get('salary/downloadSlip/{id}', 'SalaryController@downloadSlip')->name('salary.downloadslip');
  Route::get('salary/destroySlip/{id}', 'SalaryController@destroySlip')->name('salary.destroy');
  Route::get('salary/viewSalary/{id}', 'SalaryController@viewSalary')->name('salary.view');
  Route::resource('payroll', 'PayrollController')->middleware('userAuth');
  Route::get('payroll/create/{id}', 'PayrollController@create')->middleware('userAuth')->name('payroll.create')->where(['id'=>'[0-9]+']);
  // Route::resource('suggestion', 'SuggestionController',['except'=>['create']])->middleware('userAuth');
  // Route::post('suggestion/create', 'SuggestionController@create')->name('suggestion.create');
  Route::resource('suggestion', 'SuggestionController');
});


// Route::get('/', function () {
//     return view('welcome');
// });
// Route::get('noida', 'NoidaController@index');
// Route::get('hello', 'hellocontroller@hello')->middleware('test');
// Route::get('sayhello', 'hellocontroller@index');
// Route::get('test/{fname}', 'hellocontroller@test');
// Route::get('demo/{price}', function($price){
//   echo $price;
// })->where(["price"=>"[0-9]+"]);
// Route::get('price/{max}/{min?}', function($max, $min=0){
//   echo 'price is between: Max: '.$max.' and Min: '.$min;
// });

app/Suggestion.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Suggestion extends Model{
    protected $fillable = ['user_id','subject','description'];
}

app/Http/Controllers/SuggestionController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Employee;
use App\Suggestion;
use App\Notification;
use View;

class SuggestionController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(){
        $pageHeading = "Feedback Listing";
        $suggestions = Suggestion::leftJoin('employees', function($join){
            $join->on('suggestions.user_id', '=', 'employees.id');
          })
          ->orderBy('suggestions.id','desc')
          ->select('suggestions.*','employees.name','employees.email','employees.auth_id','employees.designation')
          ->paginate(5);
        return view('suggestion.index', compact('suggestions','pageHeading'))->with('i', (request()->input('page', 1) - 1) *5);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(){
        $pageHeading = "Add Feedback";
        return view('suggestion.create', compact('pageHeading'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request){
        $validate['subject'] = 'required';
        $validate['description'] = 'required';
        $request->validate($validate);
        $insert = array();
        $insert['subject'] = $request->subject;
        $insert['description'] = $request->description;
        $insert['user_id'] = $this->user->id;
        $suggestion_id = Suggestion::create($insert)->id;
        $notification['from_id'] = $this->user->id;
        $notification['to_id'] = 0;
        $notification['is_read'] = '0';
        $notification['notification_type'] = 'feedback';
        $notification['notification_url'] = route('suggestion.show',$suggestion_id);
        $notification['message'] = $this->user->name." has given feedback";
        Notification::create($notification);
        return redirect()->back()->with('success', 'Feedback submitted successfully.');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id){
        $pageHeading = "FeedBack Detail";
        $suggestion = Suggestion::leftJoin('employees', function($join){
            $join->on('suggestions.user_id', '=', 'employees.id');
          })
          ->where('suggestions.id',$id)->first([
            'suggestions.*',
            'employees.name',
            'employees.email',
            'employees.auth_id',
            'employees.designation',
          ]);
          Notification::where('notification_type','=','feedback')->where('to_id','=',0)->where('notification_url','=',route('suggestion.show',$id))->update(array('is_read'=>'1'));
        return view('suggestion.view', compact('suggestion','pageHeading'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id){
      $suggestion = Suggestion::findOrFail($id);
      $suggestion->delete();
      return back()->with('success', 'Holiday has been deleted successfully.');
    }
}

resources/views/suggestion/create.blade.php
@extends('layouts.default')
@section('content')
  <section class="content-header">
    <h1>
      Dashboard
      <small>{{ $pageHeading }}</small>
    </h1>
    <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> Dashboard</a></li>
      <li><a href="#">Feedback</a></li>
      <li class="active">{{ $pageHeading }}</li>
    </ol>
  </section>

  <!-- Main content -->
  <section class="content">
    <div class="row">
      <div class="col-xs-12">
        <div class="box">
          <div class="box-header">
            <h3 class="box-title">{{ $pageHeading }}</h3>
          </div>
          <!-- /.box-header -->
    <div class="box-body">
    @if ($errors->any())
      <div class="alert alert-danger">
        <ul>
          @foreach ($errors->all() as $error)
            <li>{{ $error }}</li>
          @endforeach
        </ul>
      </div>
    @endif
    @if($message = Session::get('success'))
      <div class="alert alert-success">
        <p>{{ $message }}</p>
      </div>
      @endif
    <form method="post" action="{{ route('suggestion.store') }}" enctype="multipart/form-data" class="form">
    @csrf
    <div class="form-group col-sm-6">
    <label for="Subject">Subject<i class="fa fa-star text-red" aria-hidden="true"></i></label>
    <input class="form-control" name="subject" value="{{ old('subject') }}" type="text" id="Subject" placeholder="Subject" required>
    </div>
    <div class="form-group col-sm-12">
    <label for="Description">Description<i class="fa fa-star text-red" aria-hidden="true"></i></label>
    <textarea class="form-control" name="description" id="Description" placeholder="Description" cols="30" rows="10">{{ old('description') }}</textarea>
    </div>
    <div class="form-group col-sm-12 text-center">
    <input class="btn btn-primary" name="add" type="submit" value="Add">
    </div>
    </form>
    </div>
          <!-- /.box-body -->
        </div>
        <!-- /.box -->
      </div>
      <!-- /.col -->
    </div>
    <!-- /.row -->
  </section>
@stop
@section('pagejs')
<script>
 $('#Date_of_Birth, #Joining_Date, #Anniversary_Date').datepicker({
    autoclose: true
  });
</script>
@stop

resources/views/suggestion/edit.blade.php
@extends('layouts.default')
@section('content')
  <section class="content-header">
    <h1>
      Dashboard
      <small>Dashboard</small>
    </h1>
    <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
      <li><a href="#">Tables</a></li>
      <li class="active">Dashboard</li>
    </ol>
  </section>

  <!-- Main content -->
  <section class="content">
    <div class="row">
      <div class="col-xs-12">
        <div class="box">
          <div class="box-header">
            <h3 class="box-title">Report</h3>
          </div>
          <!-- /.box-header -->
    <div class="box-body">
    @if ($errors->any())
      <div align="right">
        <a href="{{ route('category.index') }}" class="btn btn-default">Back</a>
      </div>
      <div class="alert alert-danger">
        <ul>
          @foreach ($errors->all() as $error)
            <li>{{ $error }}</li>
          @endforeach
        </ul>
      </div>
    @endif
    @include('flash::message')
    <form method="POST" action="{{ route('category.update', $category->id) }}" class="form">
    @csrf
    @method('PATCH')
    <div class="form-group">
    <label for="name">Category Name</label>
    <input class="form-control" name="name" type="text" id="name" value="{{ $category->name }}">
    </div>
    <input class="btn btn-info" type="submit" value="Edit">
    </form>
    </div>
          <!-- /.box-body -->
        </div>
        <!-- /.box -->
      </div>
      <!-- /.col -->
    </div>
    <!-- /.row -->
  </section>
@stop

resources/views/suggestion/index.blade.php
@extends('layouts.default')
@section('content')
  <section class="content-header">
    <h1>
      Dashboard
      <small>{{$pageHeading}}</small>
    </h1>
    <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
      <li><a href="#">Dashboard</a></li>
      <li class="active">{{$pageHeading}}</li>
    </ol>
  </section>

  <!-- Main content -->
  <section class="content">
    <div class="row">
      <div class="col-xs-12">
        <div class="box">
          <div class="box-header">
            <h3 class="box-title">{{$pageHeading}}</h3>
          </div>
          <!-- /.box-header -->
    <div class="box-body">
      @if($message = Session::get('success'))
      <div class="alert alert-success">
        <p>{{ $message }}</p>
      </div>
      @endif
      <table class="table">
        <thead class="thead-dark">
          <tr>
            <th>Sn</th><th>Employee</th><th>Subject</th><th>Date</th><th>Action</th>
          </tr>
        </thead>
        <tbody>
          @foreach($suggestions as $key=>$suggestion)
          <tr>
            <td scope="row">{{ $key+$suggestions->firstItem() }}</td>
            <td>{{ $suggestion->name }}</td>
            <td>{{ $suggestion->subject }}</td>
            <td>{{ getDateTime($suggestion->created_at, 'd F Y  h:s A') }}</td>
            <td>
              <a class="btn btn-primary" href="{{ route('suggestion.show',$suggestion->id) }}">Show</a>
              @if(in_array($user->role,array(1)))
              <form style="display:inline-block;" action="{{ route('suggestion.destroy', $suggestion->id) }}" method="post">
                @csrf
                @method('DELETE')
                <button type="submit" class="btn btn-danger">Delete</button>
              </form>
              @endif
            </td>
          </tr>
          @endforeach
        </tbody>
      </table>
      {!! $suggestions->links() !!}
    </div>
          <!-- /.box-body -->
        </div>
        <!-- /.box -->
      </div>
      <!-- /.col -->
    </div>
    <!-- /.row -->
  </section>
@stop

resources/views/suggestion/view.blade.php
@extends('layouts.default')
@section('content')
  <section class="content-header">
    <h1>
      Dashboard
      <small>{{$pageHeading}}</small>
    </h1>
    <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
      <li><a href="#">Dashboard</a></li>
      <li class="active">{{$pageHeading}}</li>
    </ol>
  </section>

  <!-- Main content -->
  <section class="content">
    <div class="row">
      <div class="col-xs-12">
      <div class="box box-primary">
            <div class="box-header with-border">
              <h3 class="box-title">{{$pageHeading}}</h3>

              <div class="box-tools pull-right">
                <a href="{{ route('suggestion.index') }}" class="btn btn-success" title=""><i class="fa fa-chevron-left"></i>Back</a>
              </div>
            </div>
            <!-- /.box-header -->
            <div class="box-body no-padding">
              <div class="mailbox-read-info">
                <h3>{{$suggestion->subject}}</h3>
                <h5>From: {{$suggestion->email}}
                  <span class="mailbox-read-time pull-right">15 Feb. 2016 11:03 PM</span></h5>
              </div>
              <div class="mailbox-read-message custom-message">
                  <pre>{{$suggestion->description}}</pre>
              </div>
            </div>
          </div>
      </div>
      <!-- /.col -->
    </div>
    <!-- /.row -->
  </section>
@stop