routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return redirect()->route('contact.create');
// });
Route::get('/', 'LoginController@index')->name('login.index');
Route::get('login', 'LoginController@index')->name('login.index');
Route::post('login', 'LoginController@processlogin')->name('login.processlogin');
Route::get('logout', 'LoginController@logout');
Route::get('forgotpassword', 'LoginController@forgotpassword')->name('login.forgotpassword');
Route::post('forgotpassword', 'LoginController@processforgotpass')->name('login.processforgotpass');
Route::get('adjustleavebalance', 'LoginController@adjustLeaveBalance');


Route::group(['middleware' => 'checkLogin'], function () {
  Route::resource('employee', 'EmployeeController')->middleware('userAuth');
  Route::get('employee/document/{id}', 'EmployeeController@document')->where(['id'=>'[0-9]+']);
  Route::post('employee/documentupload', 'EmployeeController@documentupload');
  Route::get('employee/document_edit/{id}', 'EmployeeController@document_edit')->where(['id'=>'[0-9]+']);
  Route::post('employee/document_update', 'EmployeeController@document_update');
  Route::get('employee/document_destroy/{id}', 'EmployeeController@document_destroy')->where(['id'=>'[0-9]+']);

  Route::get('dashboard', 'DashboardController@index');
  Route::get('dashboard/profile_edit', 'DashboardController@profile_edit');
  Route::post('dashboard/updateprofile', 'DashboardController@updateprofile')->name('dashboard.updateprofile');

  Route::get('leave/create', 'LeaveController@create')->name('leave.create');
  Route::post('leave/create', 'LeaveController@store')->name('leave.store');
  Route::post('leave/getDateRange', 'LeaveController@getDateRange');
  Route::get('leave', 'LeaveController@index')->name('leave.view');
  Route::get('leave/edit/{id}', 'LeaveController@edit')->where(['id'=>'[0-9]+']);
  Route::post('leave/update', 'LeaveController@update')->name('leave.update');
  Route::get('leave/leaverequests', 'LeaveController@leaverequests')->middleware('userAuth')->name('leave.leaverequests');
  Route::get('leave/detail/{id}', 'LeaveController@detail')->name('leave.detail');
  Route::post('leave/statusupdate', 'LeaveController@statusupdate')->name('leave.statusupdate');
  Route::get('leave/destroy/{id}', 'LeaveController@destroy')->where(['id'=>'[0-9]+'])->name('leave.destroy');
  Route::post('leave/getLeaveInfo', 'LeaveController@getLeaveInfo')->name('leave.info');

  Route::get('policy', 'PolicyController@index')->name('policy.index');
  Route::get('policy/edit', 'PolicyController@edit')->middleware('userAuth')->name('policy.edit');
  Route::post('policy/update', 'PolicyController@update')->name('policy.update');

  Route::resource('holiday', 'HolidayController',['except'=>['index']])->middleware('userAuth');
  Route::get('holiday', 'HolidayController@index')->name('holiday.index');

  Route::get('feedback', 'FeedbackController@index')->name('feedback.index');
  Route::post('feedback', 'FeedbackController@store')->name('feedback.store');
  Route::get('feedback/view', 'FeedbackController@view')->middleware('userAuth')->name('feedback.view');
  Route::get('feedback/getfeedback/{id}', 'FeedbackController@getfeedback')->middleware('userAuth')->name('feedback.getfeedback');
  Route::post('feedback/getPreviousChat', 'FeedbackController@getPreviousChat');

  Route::get('salary','SalaryController@index')->name('salary.index');
  Route::post('salary','SalaryController@getSalaryDetail')->name('salary.detail');
  Route::get('salary/create', 'SalaryController@create')->middleware('userAuth')->name('salary.create');
  Route::get('salary/overview/{id}', 'SalaryController@overview')->middleware('userAuth')->name('salary.overview')->where(['id'=>'[0-9]+']);
  Route::post('salary/generateSalary', 'SalaryController@generateSalary')->name('salary.generatesalary');
  Route::get('salary/downloadSlip/{id}', 'SalaryController@downloadSlip')->name('salary.downloadslip');
  Route::get('salary/destroySlip/{id}', 'SalaryController@destroySlip')->name('salary.destroy');
  Route::get('salary/viewSalary/{id}', 'SalaryController@viewSalary')->name('salary.view');
  Route::resource('payroll', 'PayrollController')->middleware('userAuth');
  Route::get('payroll/create/{id}', 'PayrollController@create')->middleware('userAuth')->name('payroll.create')->where(['id'=>'[0-9]+']);
  // Route::resource('suggestion', 'SuggestionController',['except'=>['create']])->middleware('userAuth');
  // Route::post('suggestion/create', 'SuggestionController@create')->name('suggestion.create');
  Route::resource('suggestion', 'SuggestionController');
});


// Route::get('/', function () {
//     return view('welcome');
// });
// Route::get('noida', 'NoidaController@index');
// Route::get('hello', 'hellocontroller@hello')->middleware('test');
// Route::get('sayhello', 'hellocontroller@index');
// Route::get('test/{fname}', 'hellocontroller@test');
// Route::get('demo/{price}', function($price){
//   echo $price;
// })->where(["price"=>"[0-9]+"]);
// Route::get('price/{max}/{min?}', function($max, $min=0){
//   echo 'price is between: Max: '.$max.' and Min: '.$min;
// });

app/Employee.php
<?php

namespace App;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Eloquent\Model;

class Employee extends Model{
  protected $fillable = ['name','designation','joining_date','contact_number','emergency_contact_number','dob','bank_account','bank_name','ifcs_code','pancard','leave_balance','salary','document_available','document_returned','status','image','email','auth_id','password','role','document_returned_date'];

  public function processlogin($email = ""){
    if($email!=""){
      return DB::table('employees')->where('email','=',$email)->first();
    }
  }
}

app/Http/Controllers/EmployeeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Employee;
use App\Document;
use Illuminate\Support\Str;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Mail;
use App\Mail\SendRegistrationMail;
use Illuminate\Support\Facades\Session;
use Image;

class EmployeeController extends Controller{
    public function __construct(){
      parent::__construct();
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(){
      $pageHeading = "Employee Management";
      $employees = Employee::latest()->paginate(10);
      return view('employee.index', compact('employees','pageHeading'))->with('i', (request()->input('page', 1) - 1) *10);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(){
      $pageHeading = "Add Employee";
      return view('employee.create', compact('pageHeading'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request){
        $image = $request->file('image');
        $validate['name'] = 'required';
        $validate['designation'] = 'required';
        $validate['contact_number'] = 'required|numeric';
        $validate['emergency_contact_number'] = 'required|numeric';
        $validate['dob'] = 'required|date';
        $validate['joining_date'] = 'required|date';
        //$validate['leave_balance'] = 'required';
        // $validate['salary'] = 'required';
        $validate['bank_account'] = 'required';
        $validate['bank_name'] = 'required';
        $validate['ifcs_code'] = 'required';
        $validate['pancard'] = 'required';
        $validate['document_available'] = 'required';
        $validate['document_returned'] = 'required';
        $validate['status'] = 'required';
        $validate['email'] = 'required|unique:employees|email';
        $validate['auth_id'] = 'required|unique:employees';
        $validate['password'] = 'required';
        if(!empty($image)){
          $validate['image'] = 'image|mimes:jpeg,png,jpg,gif,svg|max:2048';
        }

      $request->validate($validate);
      $insert = array();
      $insert['name'] = $request->name;
      $insert['email'] = $request->email;
      $insert['auth_id'] = $request->auth_id;
      $insert['password'] = Hash::make($request->password);
      $insert['role'] = $request->role;
      $insert['designation'] = $request->designation;
      $insert['contact_number'] = $request->contact_number;
      $insert['emergency_contact_number'] = $request->emergency_contact_number;
      $insert['dob'] = getDateTime($request->dob, 'Y-m-d');
      $insert['joining_date'] = getDateTime($request->joining_date, 'Y-m-d');
      $insert['leave_balance'] = $request->leave_balance;
      // $insert['salary'] = $request->salary;
      $insert['bank_account'] = $request->bank_account;
      $insert['bank_name'] = $request->bank_name;
      $insert['ifcs_code'] = $request->ifcs_code;
      $insert['pancard'] = $request->pancard;
      $insert['document_available'] = $request->document_available;
      $insert['document_returned'] = $request->document_returned;
      $insert['status'] = $request->status;

      if(!empty($image)){
        $insert['image'] = time().rand().'-'.str::slug($request->name, '-').'.'.$image->getClientOriginalExtension();
        $destinationPath = public_path('profile/thumbnail');
        $img = Image::make($image->getRealPath());
        $img->resize(100, 100, function ($constraint){
        $constraint->aspectRatio();})->save($destinationPath.'/'.$insert['image']);
        $image->move(public_path('profile'), $insert['image']);
      }
      Employee::create($insert);
      $data = array(
        'name' => $request->name,
        'email' => $request->email,
        'password' => $request->password,
      );
      Mail::to($request->email)->send(new SendRegistrationMail($data));
      return redirect('employee')->with('success', 'Employee Added successfully.');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id){
      $pageHeading = "Employee Detail";
      $employee = Employee::findOrFail($id);
      // if(empty($employee->image) || !file_exists('public/profile/'.$employee->image)){
      //   $employee->image = 'dummy-profile-image.jpg';
      // }
      return view('employee.view', compact('employee','pageHeading'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id){
      $pageHeading = "Update Employee";
      $employee = Employee::findOrFail($id);
      return view('employee.edit', compact('employee','pageHeading'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id){
      $image = $request->file('image');
      $validate['name'] = 'required';
      $validate['designation'] = 'required';
      $validate['contact_number'] = 'required|numeric';
      $validate['emergency_contact_number'] = 'required|numeric';
      $validate['dob'] = 'required|date';
      $validate['joining_date'] = 'required|date';
      //$validate['leave_balance'] = 'required';
      // $validate['salary'] = 'required';
      $validate['bank_account'] = 'required';
      $validate['bank_name'] = 'required';
      $validate['ifcs_code'] = 'required';
      $validate['pancard'] = 'required';
      $validate['document_available'] = 'required';
      $validate['document_returned'] = 'required';
      $validate['status'] = 'required';
      $validate['email'] = 'required|email|unique:employees,email,'.$id;
      $validate['auth_id'] = 'required|unique:employees,auth_id,'.$id;
      if(!empty($image)){
        $validate['image'] = 'image|mimes:jpeg,png,jpg,gif,svg|max:2048';
      }
      if($request->document_returned == 'yes'){
        $validate['document_returned_date'] = 'required|date';
      }

      $request->validate($validate);
      $update = array();
      $update['name'] = $request->name;
      $update['email'] = $request->email;
      $update['auth_id'] = $request->auth_id;
      if(!empty($request->password)){
        $update['password'] = Hash::make($request->password);
      }
      $update['role'] = $request->role;
      $update['designation'] = $request->designation;
      $update['contact_number'] = $request->contact_number;
      $update['emergency_contact_number'] = $request->emergency_contact_number;
      $update['dob'] = getDateTime($request->dob, 'Y-m-d');
      $update['joining_date'] = getDateTime($request->joining_date, 'Y-m-d');
      $update['leave_balance'] = $request->leave_balance;
      // $update['salary'] = $request->salary;
      $update['bank_account'] = $request->bank_account;
      $update['bank_name'] = $request->bank_name;
      $update['ifcs_code'] = $request->ifcs_code;
      $update['pancard'] = $request->pancard;
      $update['document_available'] = $request->document_available;
      $update['document_returned'] = $request->document_returned;
      if($request->document_returned == 'yes'){
        $update['document_returned_date'] = $request->document_returned_date;
      }
      $update['status'] = $request->status;
      if(!empty($image)){
        $update['image'] = time().rand().'-'.str::slug($request->name, '-').'.'.$image->getClientOriginalExtension();
        $destinationPath = public_path('profile/thumbnail');
        $img = Image::make($image->getRealPath());
        $img->resize(100, 100, function ($constraint){
        $constraint->aspectRatio();})->save($destinationPath.'/'.$update['image']);
        $image->move(public_path('profile'), $update['image']);
        if(!empty($request->old_image) && file_exists('public/profile/'.$request->old_image)){
          unlink(public_path('profile/'.$request->old_image));
        }
        if(!empty($request->old_image) && file_exists('public/profile/thumbnail/'.$request->old_image)){
          unlink(public_path('profile/thumbnail/'.$request->old_image));
        }
      }
       Employee::whereId($id)->update($update);
      return redirect('employee')->with('success', 'Employee is successfully updated');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id){
      $employee = Employee::findOrFail($id);
      $documents = Document::where('employee_id', $id)->get();
      if(!empty($documents)){
        foreach($documents as $document){
          unlink(public_path('employee_documents/'.$document->document));
          $document->delete();
        }
      }
      if(!empty($employee->image)  && file_exists('public/profile/'.$employee->image)){
        unlink(public_path('profile/'.$employee->image));
        if(file_exists('public/profile/thumbnail/'.$employee->image)){
          unlink(public_path('profile/thumbnail/'.$employee->image));
        }
      }
      $employee->delete();
      return redirect('employee')->with('success', 'Employee is successfully deleted.');
    }

    public function document($id){
      $pageHeading = "Documents";
      $data['employee_id'] = $id;
      $data['documents'] = Document::where('employee_id', $id)->get();
      return view('employee.documents', compact('data','pageHeading'));
    }

    public function documentupload(Request $request){
      $employeeId = $request->employee_id;
      $document_discription = $request->document_discription;

resources/views/employee/create.blade.php
@extends('layouts.default')
@section('content')
  <section class="content-header">
    <h1>
      Dashboard
      <small>{{ $pageHeading }}</small>
    </h1>
    <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> Dashboard</a></li>
      <li><a href="#">Employee</a></li>
      <li class="active">{{ $pageHeading }}</li>
    </ol>
  </section>

  <!-- Main content -->
  <section class="content">
    <div class="row">
      <div class="col-xs-12">
        <div class="box">
          <div class="box-header">
            <h3 class="box-title">{{ $pageHeading }}</h3>
          </div>
          <!-- /.box-header -->
    <div class="box-body">
    @if ($errors->any())
      <div class="alert alert-danger">
        <ul>
          @foreach ($errors->all() as $error)
            <li>{{ $error }}</li>
          @endforeach
        </ul>
      </div>
    @endif
    @include('flash::message')
    <form method="post" action="{{ route('employee.store') }}" enctype="multipart/form-data" class="form">
    @csrf
    <div class="form-group col-sm-6">
    <label for="Name">Employee Name<i class="fa fa-star text-red" aria-hidden="true"></i></label>
    <input class="form-control" name="name" value="{{ old('name') }}" type="text" id="Name" placeholder="Employee Name" required>
    </div>
    <div class="form-group col-sm-6">
    <label for="Designation">Designation<i class="fa fa-star text-red" aria-hidden="true"></i></label>
    <input class="form-control" name="designation" value="{{ old('designation') }}"  type="text" id="Designation" placeholder="Designation" required>
    </div>
    <div class="form-group col-sm-6">
    <label for="Email">Employee Email<i class="fa fa-star text-red" aria-hidden="true"></i></label>
    <input class="form-control" name="email" value="{{ old('email') }}" type="text" id="Email" placeholder="Employee Email" required>
    </div>
    <div class="form-group col-sm-6">
    <label for="Auth_Id">Employee Auth Id<i class="fa fa-star text-red" aria-hidden="true"></i></label>
    <input class="form-control" name="auth_id" value="{{ old('auth_id') }}" type="text" id="Auth_Id" placeholder="Employee Auth Id" required>
    </div>
    <div class="form-group col-sm-6">
    <label for="Auth_Id">Password<i class="fa fa-star text-red" aria-hidden="true"></i></label>
    <input class="form-control" name="password" type="text" id="Password" placeholder="Password" required>
    </div>
    <div class="form-group col-sm-6">
    <label for="Employee_Role">Employee Role<i class="fa fa-star text-red" aria-hidden="true"></i></label>
    <select class="form-control" name="role"  id="Employee_Role" required>
      <option value="1" {{ old('role') == '1' ? 'selected' : '' }}>Admin</option>
      <option value="2" {{ old('role') == '2' ? 'selected' : '' }}>HR</option>
      <option value="3" {{ old('role') == '3' ? 'selected' : '' }}>Employee</option>
    </select>
    </div>
    <div class="form-group col-sm-6">
    <label for="Contact_Number">Contact Number<i class="fa fa-star text-red" aria-hidden="true"></i></label>
    <input class="form-control" name="contact_number" value="{{ old('contact_number') }}" type="text" id="Contact_Number" placeholder="Contact Number" required>
    </div>
    <div class="form-group col-sm-6">
    <label for="Emergency_Contact_Number">Emergency Contact Number</label>
    <input class="form-control" name="emergency_contact_number" value="{{ old('emergency_contact_number') }}" type="text" id="Emergency_Contact_Number" placeholder="Emergency Contact Number">
    </div>
    <div class="form-group col-sm-6">
    <label for="Date_of_Birth">Date of Birth<i class="fa fa-star text-red" aria-hidden="true"></i></label>
    <input class="form-control" name="dob" value="{{ old('dob') }}" type="text" id="Date_of_Birth" class="datepickerE" data-date-format="yyyy-mm-d" placeholder="Date of Birth" autocomplete="off" required>
    </div>
    <div class="form-group col-sm-6">
    <label for="Joining_Date">Joining Date<i class="fa fa-star text-red" aria-hidden="true"></i></label>
    <input class="form-control" name="joining_date" value="{{ old('joining_date') }}" type="text" id="Joining_Date" class="datepickerE" data-date-format="yyyy-mm-d" placeholder="Joining Date"  autocomplete="off" required>
    </div>
    <div class="form-group col-sm-6">
    <label for="Leave_Balance">Leave Balance</label>
    <input class="form-control" name="leave_balance" value="0" type="text" id="Leave_Balance"  placeholder="Leave Balance"  autocomplete="off">
    </div>
    <!-- <div class="form-group col-sm-6">
    <label for="Salary">Salary<i class="fa fa-star text-red" aria-hidden="true"></i></label>
    <input class="form-control" name="salary" value="{{ old('salary') }}" type="text" id="Salary" placeholder="Salary" required>
    </div> -->
    <div class="form-group col-sm-6">
    <label for="Bank_Name">Bank Name<i class="fa fa-star text-red" aria-hidden="true"></i></label>
    <input class="form-control" name="bank_name" value="{{ old('bank_name') }}" type="text" id="Bank_Name" placeholder="Bank Name" required>
    </div>
    <div class="form-group col-sm-6">
    <label for="Bank_Account">Bank Account<i class="fa fa-star text-red" aria-hidden="true"></i></label>
    <input class="form-control" name="bank_account" value="{{ old('bank_account') }}" type="text" id="Bank_Account" placeholder="Bank Account" required>
    </div>
    <div class="form-group col-sm-6">
    <label for="IFCS_Code">IFSC Code<i class="fa fa-star text-red" aria-hidden="true"></i></label>
    <input class="form-control" name="ifcs_code" value="{{ old('ifcs_code') }}" type="text" id="IFCS_Code" placeholder="IFSC Code" required>
    </div>
    <div class="form-group col-sm-6">
    <label for="Pancard">Pancard<i class="fa fa-star text-red" aria-hidden="true"></i></label>
    <input class="form-control" name="pancard" value="{{ old('pancard') }}" type="text" id="Pancard" placeholder="Pancard" required>
    </div>
    <div class="form-group col-sm-6">
    <label for="Documents_Available">Documents Available<i class="fa fa-star text-red" aria-hidden="true"></i></label>
    <select class="form-control" name="document_available"  id="Documents_Available" required>
      <option value="yes" {{ old('document_available') == 'yes' ? 'selected' : '' }} >Yes</option>
      <option value="no" {{ old('document_available') == 'no' ? 'selected' : '' }} >No</option>
    </select>
    </div>
    <div class="form-group col-sm-6">
    <label for="Documents_Returned">Documents Returned<i class="fa fa-star text-red" aria-hidden="true"></i></label>
    <select class="form-control" name="document_returned" id="Documents_Returned" required>
      <option value="not submitted" {{ old('document_returned') == 'not submitted' ? 'selected' : ''}} >Not Submitted</option>
      <option value="yes"  {{ old('document_returned') == 'yes' ? 'selected' : ''}} >Yes</option>
      <option value="no" {{ old('document_returned') == 'no' ? 'selected' : ''}} >No</option>
    </select>
    </div>
    <div class="form-group col-sm-6">
    <label for="status">Status<i class="fa fa-star text-red" aria-hidden="true"></i></label>
    <select class="form-control" name="status" id="status" required>
      <option value="active" {{ old('status') == 'active' ? 'selected' : '' }}>Active</option>
      <option value="left" {{ old('status') == 'left' ? 'selected' : '' }}>Left</option>
    </select>
    </div>
    <div class="form-group col-sm-6">
    <label for="image">Image</label>
    <input class="form-control" name="image" type="file" id="image">
    </div>
    <div class="form-group col-sm-12 text-center">
    <input class="btn btn-primary" name="add" type="submit" value="Add">
    </div>
    </form>
    </div>
          <!-- /.box-body -->
        </div>
        <!-- /.box -->
      </div>
      <!-- /.col -->
    </div>
    <!-- /.row -->
  </section>
@stop
@section('pagejs')
<script>
 $('#Date_of_Birth, #Joining_Date, #Anniversary_Date').datepicker({
    autoclose: true
  });
</script>
@stop

resources/views/employee/document_edit.blade.php
@extends('layouts.default')
@section('content')
  <section class="content-header">
    <h1>
      Dashboard
      <small>{{ $pageHeading }}</small>
    </h1>
    <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
      <li><a href="#">Employee</a></li>
      <li class="active">{{ $pageHeading }}</li>
    </ol>
  </section>

  <!-- Main content -->
  <section class="content">
    <div class="row">
      <div class="col-xs-12">
        <div class="box">
          <div class="box-header">
            <h3 class="box-title">{{ $pageHeading }}</h3>
          </div>
          <!-- /.box-header -->
          <div class="box-body">
          @if ($errors->any())
            <div class="alert alert-danger">
              <ul>
                @foreach ($errors->all() as $error)
                  <li>{{ $error }}</li>
                @endforeach
              </ul>
            </div>
          @endif
          @if($message = Session::get('success'))
          <div class="alert alert-success">
            <p>{{ $message }}</p>
          </div>
          @endif
          <div align="right">
          <a href="{{ url('employee/document',$document->employee_id) }}" class="btn btn-success">Back</a>
          </div>
          <form method="post" action="{{ url('employee/document_update') }}" enctype="multipart/form-data" class="form">
            @csrf
          <div class="row documents-container">
            <div class="col-sm-12 document-child">
              <div class="form-group col-sm-6"><input required class="form-control" name="document_discription" value="{{ $document->document_discription }}" type="text" placeholder="Document Discription"></div>
              <div class="form-group col-sm-4"><input class="form-control" name="document_image" type="file"></div>
              <div class="form-group col-sm-2">
                <a href="{{ url('public/employee_documents',$document->document) }}" target="_blank" title="View Document"><i class="fa fa-file fa-2x"></i></a>
              </div>
            </div>
          </div>
          <div class="form-group col-sm-12 text-center">
          <input type="hidden" name="old_document" value="{{ $document->document }}">
          <input type="hidden" name="employee_id" value="{{ $document->employee_id }}">
          <input type="hidden" name="id" value="{{ $document->id }}">
          <input class="btn btn-primary" name="add" type="submit" value="Submit">
          </div>
        </form>
          </div>
          <!-- /.box-body -->
        </div>
        <!-- /.box -->
      </div>
      <!-- /.col -->
    </div>
    <!-- /.row -->
  </section>
@stop
@section('pagejs')
<script>
 $('#Date_of_Birth, #Joining_Date, #Anniversary_Date').datepicker({
    autoclose: true
  });
  $(".plus").click(function(){
    $(".documents-container").append($(".document-child:first").clone(true));
  });
  $(".minus").click(function(){
    if($(this).parent().parent().index() > 0){
      $(this).parent().parent().remove();
    }
  });
</script>
@stop

resources/views/employee/index.blade.php
@extends('layouts.default')
@section('content')
  <section class="content-header">
    <h1>
      Dashboard
      <small>{{ $pageHeading }}</small>
    </h1>
    <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> Dashboard</a></li>
      <li class="active">{{ $pageHeading }}</li>
    </ol>
  </section>

  <!-- Main content -->
  <section class="content">
    <div class="row">
      <div class="col-xs-12">
        <div class="box">
          <div class="box-header">
            <h3 class="box-title">{{ $pageHeading }}</h3>
          </div>
          <!-- /.box-header -->
    <div class="box-body">
      <div align="right">
        <a href="{{ route('employee.create') }}" class="btn btn-success">Add</a>
      </div>
      @if($message = Session::get('success'))
      <div class="alert alert-success">
        <p>{{ $message }}</p>
      </div>
      @endif
      <table class="table">
        <thead class="thead-dark">
          <tr>
            <th>Sn</th>
            <th>Name</th>
            <th>Designation</th>
            <th>Joining Date</th>
            <th>Action</th>
          </tr>
        </thead>
        <tbody>
          @if(!$employees->isEmpty())
            @foreach($employees as $key=>$employee)
            <tr>
              <td scope="row">{{ $employees->firstItem()+$key }}</td>
              <td>{{ $employee->name }}</td>
              <td>{{ $employee->designation }}</td>
              <td>{{ date('d F Y', strtotime($employee->joining_date)) }}</td>
              <td>
                <a class="btn btn-primary" href="{{ route('employee.show',$employee->id) }}">Show</a>
                <a class="btn btn-warning" href="{{ route('employee.edit',$employee->id) }}">Edit</a>
                <form style="display:inline-block;" action="{{ route('employee.destroy', $employee->id) }}" method="post">
                  @csrf
                  @method('DELETE')
                  <button type="submit" class="btn btn-danger"  onclick="return confirm('Are you sure?')">Delete</button>
                </form>
                <!-- <a class="btn btn-success" href="{{ route('salary.overview',$employee->id) }}">Payroll</a> -->
                <a class="btn btn-success" href="{{ route('payroll.create',$employee->id) }}">Payroll</a>
                @if(in_array($user->role,array(1)))
                <a class="btn btn-default" href="{{ route('salary.view',$employee->id) }}">View Salary</a>
                @endif
                @if($employee->document_available == 'yes')
                <a class="btn btn-info" href="{{ url('employee/document/'.$employee->id) }}">Documentation</a>
                @endif
              </td>
            </tr>
            @endforeach
          @else
            <tr role="row">
              <td colspan="5" class="alert alert-warning"><strong>Sorry</strong> , there is no data to display</td>
            </tr>
          @endif
        </tbody>
      </table>
      {!! $employees->links() !!}
    </div>
          <!-- /.box-body -->
        </div>
        <!-- /.box -->
      </div>
      <!-- /.col -->
    </div>
    <!-- /.row -->
  </section>
@stop