routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return redirect()->route('contact.create');
// });
Route::get('/', 'LoginController@index')->name('login.index');
Route::get('login', 'LoginController@index')->name('login.index');
Route::post('login', 'LoginController@processlogin')->name('login.processlogin');
Route::get('logout', 'LoginController@logout');
Route::get('forgotpassword', 'LoginController@forgotpassword')->name('login.forgotpassword');
Route::post('forgotpassword', 'LoginController@processforgotpass')->name('login.processforgotpass');
Route::get('adjustleavebalance', 'LoginController@adjustLeaveBalance');


Route::group(['middleware' => 'checkLogin'], function () {
  Route::resource('employee', 'EmployeeController')->middleware('userAuth');
  Route::get('employee/document/{id}', 'EmployeeController@document')->where(['id'=>'[0-9]+']);
  Route::post('employee/documentupload', 'EmployeeController@documentupload');
  Route::get('employee/document_edit/{id}', 'EmployeeController@document_edit')->where(['id'=>'[0-9]+']);
  Route::post('employee/document_update', 'EmployeeController@document_update');
  Route::get('employee/document_destroy/{id}', 'EmployeeController@document_destroy')->where(['id'=>'[0-9]+']);

  Route::get('dashboard', 'DashboardController@index');
  Route::get('dashboard/profile_edit', 'DashboardController@profile_edit');
  Route::post('dashboard/updateprofile', 'DashboardController@updateprofile')->name('dashboard.updateprofile');

  Route::get('leave/create', 'LeaveController@create')->name('leave.create');
  Route::post('leave/create', 'LeaveController@store')->name('leave.store');
  Route::post('leave/getDateRange', 'LeaveController@getDateRange');
  Route::get('leave', 'LeaveController@index')->name('leave.view');
  Route::get('leave/edit/{id}', 'LeaveController@edit')->where(['id'=>'[0-9]+']);
  Route::post('leave/update', 'LeaveController@update')->name('leave.update');
  Route::get('leave/leaverequests', 'LeaveController@leaverequests')->middleware('userAuth')->name('leave.leaverequests');
  Route::get('leave/detail/{id}', 'LeaveController@detail')->name('leave.detail');
  Route::post('leave/statusupdate', 'LeaveController@statusupdate')->name('leave.statusupdate');
  Route::get('leave/destroy/{id}', 'LeaveController@destroy')->where(['id'=>'[0-9]+'])->name('leave.destroy');
  Route::post('leave/getLeaveInfo', 'LeaveController@getLeaveInfo')->name('leave.info');

  Route::get('policy', 'PolicyController@index')->name('policy.index');
  Route::get('policy/edit', 'PolicyController@edit')->middleware('userAuth')->name('policy.edit');
  Route::post('policy/update', 'PolicyController@update')->name('policy.update');

  Route::resource('holiday', 'HolidayController',['except'=>['index']])->middleware('userAuth');
  Route::get('holiday', 'HolidayController@index')->name('holiday.index');

  Route::get('feedback', 'FeedbackController@index')->name('feedback.index');
  Route::post('feedback', 'FeedbackController@store')->name('feedback.store');
  Route::get('feedback/view', 'FeedbackController@view')->middleware('userAuth')->name('feedback.view');
  Route::get('feedback/getfeedback/{id}', 'FeedbackController@getfeedback')->middleware('userAuth')->name('feedback.getfeedback');
  Route::post('feedback/getPreviousChat', 'FeedbackController@getPreviousChat');

  Route::get('salary','SalaryController@index')->name('salary.index');
  Route::post('salary','SalaryController@getSalaryDetail')->name('salary.detail');
  Route::get('salary/create', 'SalaryController@create')->middleware('userAuth')->name('salary.create');
  Route::get('salary/overview/{id}', 'SalaryController@overview')->middleware('userAuth')->name('salary.overview')->where(['id'=>'[0-9]+']);
  Route::post('salary/generateSalary', 'SalaryController@generateSalary')->name('salary.generatesalary');
  Route::get('salary/downloadSlip/{id}', 'SalaryController@downloadSlip')->name('salary.downloadslip');
  Route::get('salary/destroySlip/{id}', 'SalaryController@destroySlip')->name('salary.destroy');
  Route::get('salary/viewSalary/{id}', 'SalaryController@viewSalary')->name('salary.view');
  Route::resource('payroll', 'PayrollController')->middleware('userAuth');
  Route::get('payroll/create/{id}', 'PayrollController@create')->middleware('userAuth')->name('payroll.create')->where(['id'=>'[0-9]+']);
  // Route::resource('suggestion', 'SuggestionController',['except'=>['create']])->middleware('userAuth');
  // Route::post('suggestion/create', 'SuggestionController@create')->name('suggestion.create');
  Route::resource('suggestion', 'SuggestionController');
});


// Route::get('/', function () {
//     return view('welcome');
// });
// Route::get('noida', 'NoidaController@index');
// Route::get('hello', 'hellocontroller@hello')->middleware('test');
// Route::get('sayhello', 'hellocontroller@index');
// Route::get('test/{fname}', 'hellocontroller@test');
// Route::get('demo/{price}', function($price){
//   echo $price;
// })->where(["price"=>"[0-9]+"]);
// Route::get('price/{max}/{min?}', function($max, $min=0){
//   echo 'price is between: Max: '.$max.' and Min: '.$min;
// });

app/Holiday.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Holiday extends Model{
  protected $fillable = ['holiday','date','type'];
}

app/Http/Controllers/HolidayController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Holiday;

class HolidayController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(){
      $pageHeading = "Holiday List";
      $year = date('Y');
      $normalHolidays = Holiday::where('type','=',1)->whereYear('date', $year)->orderBy('date','ASC')->get();
      $restrictedHolidays = Holiday::where('type','=',2)->whereYear('date', $year)->orderBy('date','ASC')->get();
      return view('holiday.index', compact('pageHeading','normalHolidays','restrictedHolidays'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(){
      $pageHeading = "Add Holiday";
      $holidays = Holiday::orderBy('date','ASC')->get();
      return view('holiday.create', compact('pageHeading','holidays'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request){
      $dates = $request->date;
      $holiday = $request->holiday;
      $type = $request->type;
      if(is_array($dates)){
        foreach($dates as $key=>$date){
          $insert = array();
          $insert['holiday'] = ucwords($holiday[$key]);
          $insert['date'] = $date;
          $insert['type'] = $type[$key];
          Holiday::create($insert);
        }
        return back()->with('success', 'Holiday has been added successfully.');
      }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
     public function destroy($id){
       $holiday = Holiday::findOrFail($id);
       $holiday->delete();
       return back()->with('success', 'Holiday has been deleted successfully.');
     }
}

resources/views/holiday/create.blade.php
@extends('layouts.default')
@section('content')
  <section class="content-header">
    <h1>
      Dashboard
      <small>{{ $pageHeading }}</small>
    </h1>
    <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> Dashboard</a></li>
      <li><a href="#">Holiday</a></li>
      <li class="active">{{ $pageHeading }}</li>
    </ol>
  </section>

  <!-- Main content -->
  <section class="content">
    <div class="row">
      <div class="col-xs-12">
        <div class="box">
          <div class="box-header">
            <h3 class="box-title">{{ $pageHeading }}</h3>
          </div>
          <!-- /.box-header -->
    <div class="box-body">
      @if($message = Session::get('success'))
      <div class="alert alert-success">
        <p>{{ $message }}</p>
      </div>
      @endif
      <div class="form-group col-sm-3">
        <a href="#" class="btn btn-success plus"><i class="fa fa-plus"></i>&nbsp;Add</a>
        <a href="#" class="btn btn-warning minus"><i class="fa fa-minus"></i>&nbsp;Remove</a>
      </div>
      <div align="right">
        <a href="{{ route('employee.index') }}" class="btn btn-success">Back</a>
      </div>
      <form method="post" action="{{ route('holiday.store') }}" enctype="multipart/form-data" class="form">
        @csrf
      <div class="row documents-container">
        <div class="col-sm-12 document-child">
          <div class="form-group col-sm-3"><input required class="form-control" name="holiday[]" type="text" placeholder="Holiday Name"></div>
          <div class="form-group col-sm-3"><input required id="cal-0" class="form-control holidayDate" name="date[]" type="text" data-date-format="yyyy-mm-d" placeholder="Holiday Date" autocomplete="off"></div>
          <div class="form-group col-sm-4">
            <select class="form-control" name="type[]">
              <option value="1">Normal Holiday</option>
              <option value="2">Restricted Holiday</option>
            </select>
          </div>
        </div>
      </div>
      <div class="form-group col-sm-12 text-center">
      <input class="btn btn-primary" name="add" type="submit" value="Submit">
      </div>
    </form>
    </div>
          <!-- /.box-body -->
        </div>
        <div class="box">
          <div class="box-header">
            <h3 class="box-title">{{ $pageHeading }}</h3>
          </div>
          <!-- /.box-header -->
    <div class="box-body">
      <table class="table">
        <thead class="thead-dark">
          <tr>
            <th>Sn</th>
            <th>Holiday</th>
            <th>Date</th>
            <th>Type</th>
            <th>Action</th>
          </tr>
        </thead>
        <tbody>
          @if(!$holidays->isEmpty())
           @foreach($holidays as $key=>$holiday)
           <tr>
             <td scope="row">{{ $key+1 }}</td>
             <td>{{ $holiday->holiday }}</td>
             <td>{{ date('d F Y', strtotime($holiday->date)) }}</td>
             <td>@if($holiday->type == 1) {{ 'Normal Holiday' }} @else {{ 'Restricted Holiday' }} @endif</td>
             <td>
               <form style="display:inline-block;" action="{{ route('holiday.destroy', $holiday->id) }}" method="post">
                 @csrf
                 @method('DELETE')
                 <button type="submit" class="btn btn-danger">Delete</button>
               </form>
             </td>
           </tr>
           @endforeach
          @else
            <tr role="row">
              <td colspan="5" class="alert alert-warning"><strong>Sorry</strong> , there is no data to display</td>
            </tr>
          @endif
        </tbody>
      </table>
    </div>
          <!-- /.box-body -->
        </div>
        <!-- /.box -->
      </div>
      <!-- /.col -->
    </div>
    <!-- /.row -->
  </section>
@stop
@section('pagejs')
<script type="text/javascript">
  $("#cal-0").datepicker({autoclose: true,orientation:"down"});
  $(".plus").click(function(){
    $(".documents-container").append($(".document-child:first").clone(false));
    $(".holidayDate").attr('id');
    $(".holidayDate").each(function(index, value){
      var elementId = 'index-'+index;
      $(value).attr('id', elementId);
      $("#"+elementId).datepicker({autoclose: true,orientation:"down"});
    });
  });
  $(".minus").click(function(){
    if($(".document-child:last").index() > 0){
      $(".document-child:last").remove();
    }
  });
</script>
@stop

resources/views/holiday/index.blade.php
@extends('layouts.default')
@section('content')
  <section class="content-header">
    <h1>
      Dashboard
      <small>{{ $pageHeading }}</small>
    </h1>
    <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> Dashboard</a></li>
      <li><a href="#">Holiday</a></li>
      <li class="active">{{ $pageHeading }}</li>
    </ol>
  </section>

  <!-- Main content -->
  <section class="content">
    <div class="row">
      <div class="col-xs-12">
        <div class="box">
          <div class="box-header">
            <h3 class="box-title">{{ $pageHeading }}</h3>
          </div>
          <!-- /.box-header -->
    <div class="box-body">
      @if($message = Session::get('success'))
      <div class="alert alert-success">
        <p>{{ $message }}</p>
      </div>
      @endif
      <div class="row">
        <div class="col-sm-6">
          <div class="box box-success">
            <div class="box-body box-profile">
              <h3 class="profile-username text-center">Holidays</h3>
              <table class="table">
                <thead class="thead-dark">
                  <tr>
                    <th>Sn</th>
                    <th>Holiday</th>
                    <th>Date</th>
                  </tr>
                </thead>
                <tbody>
                  @if(!$normalHolidays->isEmpty())
                   @foreach($normalHolidays as $key=>$holiday)
                   <tr>
                     <td scope="row">{{ $key+1 }}</td>
                     <td>{{ $holiday->holiday }}</td>
                     <td>{{ date('d F Y', strtotime($holiday->date)) }}</td>
                   </tr>
                   @endforeach
                  @else
                    <tr role="row">
                      <td colspan="3" class="alert alert-warning"><strong>Sorry</strong> , there is no data to display</td>
                    </tr>
                  @endif
                </tbody>
              </table>
            </div>
            <!-- /.box-body -->
          </div>
        </div>
        <div class="col-sm-6">
          <div class="box box-danger">
            <div class="box-body box-profile">
              <h3 class="profile-username text-center">Restricted Holidays</h3>
              <table class="table">
                <thead class="thead-dark">
                  <tr>
                    <th>Sn</th>
                    <th>Holiday</th>
                    <th>Date</th>
                  </tr>
                </thead>
                <tbody>
                  @if(!$restrictedHolidays->isEmpty())
                   @foreach($restrictedHolidays as $key=>$holiday)
                   <tr>
                     <td scope="row">{{ $key+1 }}</td>
                     <td>{{ $holiday->holiday }}</td>
                     <td>{{ date('d F Y', strtotime($holiday->date)) }}</td>
                   </tr>
                   @endforeach
                  @else
                    <tr role="row">
                      <td colspan="3" class="alert alert-warning"><strong>Sorry</strong> , there is no data to display</td>
                    </tr>
                  @endif
                </tbody>
              </table>
            </div>
            <!-- /.box-body -->
          </div>
        </div>
      </div>
    </div>
          <!-- /.box-body -->
        </div>
        <!-- /.box -->
      </div>
      <!-- /.col -->
    </div>
    <!-- /.row -->
  </section>
@stop