routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return redirect()->route('contact.create');
// });
Route::get('/', 'LoginController@index')->name('login.index');
Route::get('login', 'LoginController@index')->name('login.index');
Route::post('login', 'LoginController@processlogin')->name('login.processlogin');
Route::get('logout', 'LoginController@logout');
Route::get('forgotpassword', 'LoginController@forgotpassword')->name('login.forgotpassword');
Route::post('forgotpassword', 'LoginController@processforgotpass')->name('login.processforgotpass');
Route::get('adjustleavebalance', 'LoginController@adjustLeaveBalance');


Route::group(['middleware' => 'checkLogin'], function () {
  Route::resource('employee', 'EmployeeController')->middleware('userAuth');
  Route::get('employee/document/{id}', 'EmployeeController@document')->where(['id'=>'[0-9]+']);
  Route::post('employee/documentupload', 'EmployeeController@documentupload');
  Route::get('employee/document_edit/{id}', 'EmployeeController@document_edit')->where(['id'=>'[0-9]+']);
  Route::post('employee/document_update', 'EmployeeController@document_update');
  Route::get('employee/document_destroy/{id}', 'EmployeeController@document_destroy')->where(['id'=>'[0-9]+']);

  Route::get('dashboard', 'DashboardController@index');
  Route::get('dashboard/profile_edit', 'DashboardController@profile_edit');
  Route::post('dashboard/updateprofile', 'DashboardController@updateprofile')->name('dashboard.updateprofile');

  Route::get('leave/create', 'LeaveController@create')->name('leave.create');
  Route::post('leave/create', 'LeaveController@store')->name('leave.store');
  Route::post('leave/getDateRange', 'LeaveController@getDateRange');
  Route::get('leave', 'LeaveController@index')->name('leave.view');
  Route::get('leave/edit/{id}', 'LeaveController@edit')->where(['id'=>'[0-9]+']);
  Route::post('leave/update', 'LeaveController@update')->name('leave.update');
  Route::get('leave/leaverequests', 'LeaveController@leaverequests')->middleware('userAuth')->name('leave.leaverequests');
  Route::get('leave/detail/{id}', 'LeaveController@detail')->name('leave.detail');
  Route::post('leave/statusupdate', 'LeaveController@statusupdate')->name('leave.statusupdate');
  Route::get('leave/destroy/{id}', 'LeaveController@destroy')->where(['id'=>'[0-9]+'])->name('leave.destroy');
  Route::post('leave/getLeaveInfo', 'LeaveController@getLeaveInfo')->name('leave.info');

  Route::get('policy', 'PolicyController@index')->name('policy.index');
  Route::get('policy/edit', 'PolicyController@edit')->middleware('userAuth')->name('policy.edit');
  Route::post('policy/update', 'PolicyController@update')->name('policy.update');

  Route::resource('holiday', 'HolidayController',['except'=>['index']])->middleware('userAuth');
  Route::get('holiday', 'HolidayController@index')->name('holiday.index');

  Route::get('feedback', 'FeedbackController@index')->name('feedback.index');
  Route::post('feedback', 'FeedbackController@store')->name('feedback.store');
  Route::get('feedback/view', 'FeedbackController@view')->middleware('userAuth')->name('feedback.view');
  Route::get('feedback/getfeedback/{id}', 'FeedbackController@getfeedback')->middleware('userAuth')->name('feedback.getfeedback');
  Route::post('feedback/getPreviousChat', 'FeedbackController@getPreviousChat');

  Route::get('salary','SalaryController@index')->name('salary.index');
  Route::post('salary','SalaryController@getSalaryDetail')->name('salary.detail');
  Route::get('salary/create', 'SalaryController@create')->middleware('userAuth')->name('salary.create');
  Route::get('salary/overview/{id}', 'SalaryController@overview')->middleware('userAuth')->name('salary.overview')->where(['id'=>'[0-9]+']);
  Route::post('salary/generateSalary', 'SalaryController@generateSalary')->name('salary.generatesalary');
  Route::get('salary/downloadSlip/{id}', 'SalaryController@downloadSlip')->name('salary.downloadslip');
  Route::get('salary/destroySlip/{id}', 'SalaryController@destroySlip')->name('salary.destroy');
  Route::get('salary/viewSalary/{id}', 'SalaryController@viewSalary')->name('salary.view');
  Route::resource('payroll', 'PayrollController')->middleware('userAuth');
  Route::get('payroll/create/{id}', 'PayrollController@create')->middleware('userAuth')->name('payroll.create')->where(['id'=>'[0-9]+']);
  // Route::resource('suggestion', 'SuggestionController',['except'=>['create']])->middleware('userAuth');
  // Route::post('suggestion/create', 'SuggestionController@create')->name('suggestion.create');
  Route::resource('suggestion', 'SuggestionController');
});


// Route::get('/', function () {
//     return view('welcome');
// });
// Route::get('noida', 'NoidaController@index');
// Route::get('hello', 'hellocontroller@hello')->middleware('test');
// Route::get('sayhello', 'hellocontroller@index');
// Route::get('test/{fname}', 'hellocontroller@test');
// Route::get('demo/{price}', function($price){
//   echo $price;
// })->where(["price"=>"[0-9]+"]);
// Route::get('price/{max}/{min?}', function($max, $min=0){
//   echo 'price is between: Max: '.$max.' and Min: '.$min;
// });

app/Feedback.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Feedback extends Model{
  protected $fillable = ['employee_id','message_from','message','is_read'];
}

app/Http/Controllers/FeedbackController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Feedback;
use App\Employee;
use View;
class FeedbackController extends Controller{
  public function __construct(){
    parent::__construct();
  }

  public function index(){
    $pageHeading = "Send Feedback";
    $messages = Feedback::leftJoin('employees', function($join){
      $join->on('feedback.message_from', '=', 'employees.id');
    })
    ->where('feedback.employee_id','=',$this->user->id)->orderBy('feedback.created_at','DESC')->take(8)
    ->get([
      'feedback.*',
      'employees.name',
      'employees.image'
    ]);
    Feedback::where('employee_id','=',$this->user->id)->where('message_from','!=',$this->user->id)->update(array('is_read'=>1));
    $messages = $messages->reverse();
    return view('feedback.index', compact('pageHeading','messages'));
  }

  public function store(Request $request){
    $validate['message'] = 'required';
    $request->validate($validate);
    $insert['employee_id'] = $request->employee_id;
    if(!empty($request->message_from)){
      $insert['message_from'] = $request->message_from;
    }
    else{
      $insert['message_from'] = $request->employee_id;
    }
    $insert['message'] = $request->message;
    $insert['is_read'] = 0;
    Feedback::create($insert);
    if(!empty($request->message_from)){
      return redirect('feedback/getfeedback/'.$request->employee_id)->with('success', 'Message has been sent success');
    }
    else{
      return redirect('feedback')->with('success', 'Message has been sent success');
    }
  }

  public function view(){
    $pageHeading = "Employee Feedbacks";
    $employees = Employee::where('status','=','active')->get();
    return view('feedback.view', compact('pageHeading','employees'));
  }

  public function getfeedback($id){
    $pageHeading = "Send Feedback";
    $messages = Feedback::leftJoin('employees', function($join){
      $join->on('feedback.message_from', '=', 'employees.id');
    })
    ->where('feedback.employee_id','=',$id)->orderBy('feedback.created_at','DESC')->take(8)
    ->get([
      'feedback.*',
      'employees.name',
      'employees.image'
    ]);
    Feedback::where('employee_id','=',$id)->where('message_from','=',$id)->update(array('is_read'=>1));
    $data['employee_id'] = $id;
    $messages = $messages->reverse();
    return view('feedback.getfeedback', compact('pageHeading','messages','data'));
  }

  public function getPreviousChat(Request $request){
    $response = array();
    $feedback_id = $request->feedback_id;
    $employee_id = $request->employee_id;
    $is_admin = $request->is_admin;
    $messages = Feedback::leftJoin('employees', function($join){
      $join->on('feedback.message_from', '=', 'employees.id');
    })
    ->where('feedback.employee_id','=',$employee_id)
    ->where('feedback.id','<',$feedback_id)
    ->orderBy('feedback.created_at','DESC')
    ->take(8)
    ->get([
      'feedback.*',
      'employees.name',
      'employees.image'
    ]);
    $messages = $messages->reverse();
    $response['feedback_count'] = (count($messages) > 0)?count($messages):0;
    $response['feedbacks'] = View::make('feedback.previousfeedbackmessages',compact('messages','is_admin'))->render();
    sendResponse($response);
  }
}

resources/views/feedback/getfeedback.blade.php
@extends('layouts.default')
@section('content')
  <section class="content-header">
    <h1>
      Dashboard
      <small>{{ $pageHeading }}</small>
    </h1>
    <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> Dashboard</a></li>
      <li><a href="#">Feedback</a></li>
      <li class="active">{{ $pageHeading }}</li>
    </ol>
  </section>

  <!-- Main content -->
  <section class="content">
    <div class="row">
      <div class="col-xs-12">
        <div class="box">
          <div class="box-header">
            <h3 class="box-title">{{ $pageHeading }}</h3>
          </div>
          <!-- /.box-header -->
    <div class="box-body">
      <div class="row">
        <div class="col-sm-12">
          <div class="box box-success">
            <div class="box-body box-profile">
              <h3 class="profile-username text-center">Messages</h3>
              <div class="chat-custom-container">
                @if(!$messages->isEmpty())
                  @foreach($messages as $key=>$message)
                    @if($message->employee_id == $message->message_from)
                      <div class="chat-container" id="feedback-{{ $message->id }}{{ $message->employee_id }}"  chat-id="{{ $message->id }}" employee-id="{{ $message->employee_id }}">
                      <img src="@if($message->image!='' && file_exists('public/profile/'.$message->image)) {{ url('public/profile', $message->image) }} @else {{ url('public/profile/dummy-profile-image.jpg') }} @endif" alt="Avatar">
                      <p>{{ $message->message }}</p>
                      <span class="time-right"><strong>{{ $message->name }}</strong>&nbsp;&nbsp;{{ getDateTime($message->created_at,'d F Y h:i a') }}</span>
                      </div>
                    @else
                      <div class="chat-container darker" id="feedback-{{ $message->id }}{{ $message->employee_id }}" chat-id="{{ $message->id }}" employee-id="{{ $message->employee_id }}">
                      <img src="@if($message->image!='' && file_exists('public/profile/'.$message->image)) {{ url('public/profile', $message->image) }} @else {{ url('public/profile/dummy-profile-image.jpg') }} @endif" alt="Avatar" class="right">
                      <p>{{ $message->message }}</p>
                      <span class="time-left"><strong>{{ $message->name }}</strong>&nbsp;&nbsp;<i class="@if($message->is_read == 1) {{ 'fa fa-eye text-green' }} @else {{ 'fa fa-eye-slash' }} @endif" aria-hidden="true"></i>&nbsp;{{ getDateTime($message->created_at,'d F Y h:i a') }}</span>
                      </div>
                    @endif
                  @endforeach
                @endif
            </div>
            </div>
            <!-- /.box-body -->
          </div>
        </div>
        <div class="col-sm-12">
          <div class="box box-success">
            <div class="box-body box-profile">
              @include('flash::message')
              @if($message = Session::get('success'))
              <div class="alert alert-success">
                <p>{{ $message }}</p>
              </div>
              @endif
              <form method="post" action="{{ route('feedback.store') }}" enctype="multipart/form-data" class="form">
              @csrf
              <div class="form-group col-sm-12">
              <label for="Reason">Message</label>
              <input class="form-control" name="message" value="{{ old('message') }}" type="text" id="Reason" placeholder="Reason">
              </div>
              <div class="form-group col-sm-12 text-center">
              <input type="hidden" name="employee_id" value="{{ $data['employee_id'] }}">
              <input type="hidden" name="message_from" value="{{ $user->id }}">
              <input class="btn btn-primary" name="add" type="submit" value="Send">
              <a href="{{ route('feedback.getfeedback',$data['employee_id']) }}" class="btn btn-info">Refresh</a>
              </div>
              </form>
            </div>
            <!-- /.box-body -->
          </div>
        </div>
      </div>
    </div>
          <!-- /.box-body -->
        </div>
        <!-- /.box -->
      </div>
      <!-- /.col -->
    </div>
    <!-- /.row -->
  </section>
@stop
@section('pagejs')
<script type="text/javascript">
  $(".chat-custom-container").animate({ scrollTop: $('.chat-custom-container').prop("scrollHeight")}, 1000);
  $(".chat-custom-container").bind("scroll", function() {
    if($(this).scrollTop() == 0){
      console.log("hit request");
      var feedback_id = $(".chat-container:first").attr('chat-id');
      var employee_id = $(".chat-container:first").attr('employee-id');
      getPreviousChat(feedback_id, employee_id);
    }
  });

  $.ajaxSetup({
    headers: {
      'X-CSRF-TOKEN': $('input[name="_token"]').val()
    }
  });

  var getPreviousChat = function(feedback_id, employee_id){
    $.ajax({
      url:'{{ url('feedback/getPreviousChat')}}',
      method:'post',
      data:{feedback_id:feedback_id,employee_id:employee_id,is_admin:1},
      dataType:'json',
      beforeSend: function(){
        console.log("+++++Requesting+++++");
      },
      success: function(json){
        if(json.feedback_count > 0){
          $(".chat-custom-container").prepend(json.feedbacks);
          $('.chat-custom-container').scrollTop(50);
        }
      }
    })
  }
</script>
@stop

resources/views/feedback/index.blade.php
@extends('layouts.default')
@section('content')
  <section class="content-header">
    <h1>
      Dashboard
      <small>{{ $pageHeading }}</small>
    </h1>
    <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> Dashboard</a></li>
      <li><a href="#">Feedback</a></li>
      <li class="active">{{ $pageHeading }}</li>
    </ol>
  </section>

  <!-- Main content -->
  <section class="content">
    <div class="row">
      <div class="col-xs-12">
        <div class="box">
          <div class="box-header">
            <h3 class="box-title">{{ $pageHeading }}</h3>
          </div>
          <!-- /.box-header -->
    <div class="box-body">
      <div class="row">
        <div class="col-sm-12">
          <div class="box box-success">
            <div class="box-body box-profile">
              <h3 class="profile-username text-center">Messages</h3>
              <div class="chat-custom-container">
              @if(!$messages->isEmpty())
                @foreach($messages as $key=>$message)
                  @if($message->employee_id == $message->message_from)
                    <div class="chat-container darker" id="feedback-{{ $message->id }}{{ $message->employee_id }}" chat-id="{{ $message->id }}" employee-id="{{ $message->employee_id }}">
                    <img src="@if($message->image!='' && file_exists('public/profile/'.$message->image)) {{ url('public/profile', $message->image) }} @else {{ url('public/profile/dummy-profile-image.jpg') }} @endif" alt="Avatar" class="right">
                    <p>{{ $message->message }}</p>
                    <span class="time-left"><strong>{{ $message->name }}</strong>&nbsp;&nbsp;<i class="@if($message->is_read == 1) {{ 'fa fa-eye text-green' }} @else {{ 'fa fa-eye-slash' }} @endif" aria-hidden="true"></i>&nbsp;{{ getDateTime($message->created_at,'d F Y h:i a') }}</span>
                    </div>
                  @else
                    <div class="chat-container" id="feedback-{{ $message->id }}{{ $message->employee_id }}"  chat-id="{{ $message->id }}" employee-id="{{ $message->employee_id }}">
                    <img src="@if($message->image!='' && file_exists('public/profile/'.$message->image)) {{ url('public/profile', $message->image) }} @else {{ url('public/profile/dummy-profile-image.jpg') }} @endif" alt="Avatar">
                    <p>{{ $message->message }}</p>
                    <span class="time-right"><strong>{{ $message->name }}</strong>&nbsp;&nbsp;{{ getDateTime($message->created_at,'d F Y h:i a') }}</span>
                    </div>
                  @endif
                @endforeach
              @endif
            </div>
            </div>
            <!-- /.box-body -->
          </div>
        </div>
        <div class="col-sm-12">
          <div class="box box-success">
            <div class="box-body box-profile">
              @include('flash::message')
              @if($message = Session::get('success'))
              <div class="alert alert-success">
                <p>{{ $message }}</p>
              </div>
              @endif
              <form method="post" action="{{ route('feedback.store') }}" enctype="multipart/form-data" class="form">
              @csrf
              <div class="form-group col-sm-12">
              <label for="Reason">Message</label>
              <input class="form-control" name="message" value="{{ old('message') }}" type="text" id="Reason" placeholder="Reason">
              </div>
              <div class="form-group col-sm-12 text-center">
              <input type="hidden" name="employee_id" value="{{ $user->id }}">
              <input class="btn btn-primary" name="add" type="submit" value="Send">
              <a href="{{ route('feedback.index') }}" class="btn btn-info">Refresh</a>
              </div>
              </form>
            </div>
            <!-- /.box-body -->
          </div>
        </div>
      </div>
    </div>
          <!-- /.box-body -->
        </div>
        <!-- /.box -->
      </div>
      <!-- /.col -->
    </div>
    <!-- /.row -->
  </section>
@stop
@section('pagejs')
<script type="text/javascript">
  $(".chat-custom-container").animate({ scrollTop: $('.chat-custom-container').prop("scrollHeight")}, 1000);
  $(".chat-custom-container").bind("scroll", function() {
    if($(this).scrollTop() == 0){
      console.log("hit request");
      var feedback_id = $(".chat-container:first").attr('chat-id');
      var employee_id = $(".chat-container:first").attr('employee-id');
      getPreviousChat(feedback_id, employee_id);
    }
  });

  $.ajaxSetup({
    headers: {
      'X-CSRF-TOKEN': $('input[name="_token"]').val()
    }
  });

  var getPreviousChat = function(feedback_id, employee_id){
    $.ajax({
      url:'{{ url('feedback/getPreviousChat')}}',
      method:'post',
      data:{feedback_id:feedback_id,employee_id:employee_id,is_admin:0},
      dataType:'json',
      beforeSend: function(){
        console.log("+++++Requesting+++++");
      },
      success: function(json){
        if(json.feedback_count > 0){
          $(".chat-custom-container").prepend(json.feedbacks);
          $('.chat-custom-container').scrollTop(50);
        }
      }
    })
  }
</script>
@stop

resources/views/feedback/previousfeedbackmessages.blade.php
@if(!$messages->isEmpty())
  @if($is_admin == 0)
    @foreach($messages as $key=>$message)
      @if($message->employee_id == $message->message_from)
        <div class="chat-container darker" id="feedback-{{ $message->id }}{{ $message->employee_id }}" chat-id="{{ $message->id }}" employee-id="{{ $message->employee_id }}">
        <img src="@if($message->image!='' && file_exists('public/profile/'.$message->image)) {{ url('public/profile', $message->image) }} @else {{ url('public/profile/dummy-profile-image.jpg') }} @endif" alt="Avatar" class="right">
        <p>{{ $message->message }}</p>
        <span class="time-left"><strong>{{ $message->name }}</strong>&nbsp;&nbsp;<i class="@if($message->is_read == 1) {{ 'fa fa-eye text-green' }} @else {{ 'fa fa-eye-slash' }} @endif" aria-hidden="true"></i>&nbsp;{{ getDateTime($message->created_at,'d F Y h:i a') }}</span>
        </div>
      @else
        <div class="chat-container" id="feedback-{{ $message->id }}{{ $message->employee_id }}"  chat-id="{{ $message->id }}" employee-id="{{ $message->employee_id }}">
        <img src="@if($message->image!='' && file_exists('public/profile/'.$message->image)) {{ url('public/profile', $message->image) }} @else {{ url('public/profile/dummy-profile-image.jpg') }} @endif" alt="Avatar">
        <p>{{ $message->message }}</p>
        <span class="time-right"><strong>{{ $message->name }}</strong>&nbsp;&nbsp;{{ getDateTime($message->created_at,'d F Y h:i a') }}</span>
        </div>
      @endif
    @endforeach
  @else
  @foreach($messages as $key=>$message)
    @if($message->employee_id == $message->message_from)
      <div class="chat-container" id="feedback-{{ $message->id }}{{ $message->employee_id }}"  chat-id="{{ $message->id }}" employee-id="{{ $message->employee_id }}">
      <img src="@if($message->image!='' && file_exists('public/profile/'.$message->image)) {{ url('public/profile', $message->image) }} @else {{ url('public/profile/dummy-profile-image.jpg') }} @endif" alt="Avatar">
      <p>{{ $message->message }}</p>
      <span class="time-right"><strong>{{ $message->name }}</strong>&nbsp;&nbsp;{{ getDateTime($message->created_at,'d F Y h:i a') }}</span>
      </div>
    @else
    <div class="chat-container darker" id="feedback-{{ $message->id }}{{ $message->employee_id }}" chat-id="{{ $message->id }}" employee-id="{{ $message->employee_id }}">
    <img src="@if($message->image!='' && file_exists('public/profile/'.$message->image)) {{ url('public/profile', $message->image) }} @else {{ url('public/profile/dummy-profile-image.jpg') }} @endif" alt="Avatar" class="right">
    <p>{{ $message->message }}</p>
    <span class="time-left"><strong>{{ $message->name }}</strong>&nbsp;&nbsp;<i class="@if($message->is_read == 1) {{ 'fa fa-eye text-green' }} @else {{ 'fa fa-eye-slash' }} @endif" aria-hidden="true"></i>&nbsp;{{ getDateTime($message->created_at,'d F Y h:i a') }}</span>
    </div>
    @endif
  @endforeach
  @endif

@endif

resources/views/feedback/view.blade.php
@extends('layouts.default')
@section('content')
  <section class="content-header">
    <h1>
      Dashboard
      <small>{{ $pageHeading }}</small>
    </h1>
    <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> Dashboard</a></li>
      <li class="active">{{ $pageHeading }}</li>
    </ol>
  </section>

  <!-- Main content -->
  <section class="content">
    <div class="row">
      <div class="col-xs-12">
        <div class="box">
          <div class="box-header">
            <h3 class="box-title">{{ $pageHeading }}</h3>
          </div>
          <!-- /.box-header -->
    <div class="box-body">
      <div align="right">
        <a href="{{ route('employee.create') }}" class="btn btn-success">Add</a>
      </div>
      @if($message = Session::get('success'))
      <div class="alert alert-success">
        <p>{{ $message }}</p>
      </div>
      @endif
      <table class="table">
        <thead class="thead-dark">
          <tr>
            <th>Sn</th>
            <th>Name</th>
            <th>Designation</th>
            <th>Joining Date</th>
            <th>Action</th>
          </tr>
        </thead>
        <tbody>
          @if(!$employees->isEmpty())
            @foreach($employees as $key=>$employee)
            <tr>
              <td scope="row">{{ $key+1 }}</td>
              <td>{{ $employee->name }}</td>
              <td>{{ $employee->designation }}</td>
              <td>{{ date('d F Y', strtotime($employee->joining_date)) }}</td>
              <td>
                <a class="btn btn-primary" href="{{ route('feedback.getfeedback',$employee->id) }}">Feedback</a>
              </td>
            </tr>
            @endforeach
          @else
            <tr role="row">
              <td colspan="5" class="alert alert-warning"><strong>Sorry</strong> , there is no data to display</td>
            </tr>
          @endif
        </tbody>
      </table>
    </div>
          <!-- /.box-body -->
        </div>
        <!-- /.box -->
      </div>
      <!-- /.col -->
    </div>
    <!-- /.row -->
  </section>
@stop